package com.sunwell.stock.utils;

public class StandardConstant {
	public static final int NO_ERROR = 0;
//	public static final int ERROR_INTERNAL_SERVER = 1;
//    public static final int ERROR_NO_LOGIN_SESSION = 2;
//    public static final int ERROR_NOT_ACTIVE = 3;
//	public static final int ERROR_BAD_REQUEST = 4;
//	public static final int TOKEN_VALID = 5;
//	public static final int ERROR_TOKEN_INVALID = ;
//	public static final int ERROR_TOKEN_EXPIRED = 29;
//    public static final int ERROR_CANT_FIND_TENANT = 0;
    public static final int ERROR_CANT_FIND_USER = 1;
    public static final int ERROR_CANT_FIND_CATEGORY = 2;
    public static final int ERROR_CANT_FIND_CUSTOMER = 3;
    public static final int ERROR_CANT_FIND_INVOICE = 4;
    public static final int ERROR_CANT_FIND_PRODUCT = 5;
    public static final int ERROR_CANT_FIND_INVOICE_ITEM = 6;
    public static final int ERROR_CANT_FIND_PAYMENT_METHOD = 7;
    public static final int ERROR_CANT_FIND_USER_GROUP = 8;
    public static final int ERROR_CANT_FIND_WAREHOUSE = 9;
    public static final int ERROR_CANT_FIND_PAYMENT = 10;
    public static final int ERROR_CANT_FIND_MERK = 11;
    public static final int ERROR_CANT_FIND_SHIPMENT = 12;
    public static final int ERROR_CANT_FIND_METRIC = 13;
    public static final int ERROR_CANT_FIND_SALES_ORDER = 14;
    public static final int ERROR_CANT_FIND_STOCK_RESERVATION = 15;
    public static final int ERROR_CANT_FIND_DELIVERY_ORDER = 16;
    public static final int ERROR_CANT_FIND_SALES_RETURN = 17;
    public static final int ERROR_CANT_FIND_CART_DETAIL = 18;
    public static final int ERROR_CANT_FIND_SALES_OFFICER = 19;
    public static final int ERROR_CANT_FIND_STOCK = 20;
    public static final int ERROR_CANT_FIND_SELL_PRICE = 21;
    public static final int ERROR_CANT_FIND_PRODUCT_IMAGE = 22;
    public static final int ERROR_CANT_FIND_PAYMENT_IMAGE = 23;
    public static final int ERROR_CONSTRAINT = 600;
    public static final int ERROR_NO_ITEM = 201;
    public static final int ERROR_NO_EMAIL = 202;
    public static final int ERROR_NO_PASSWORD = 203;
    public static final int ERROR_NO_CUSTOMER = 204;
    public static final int ERROR_NO_OBJECT = 205;
    public static final int ERROR_NOT_ENOUGH_STOCK = 206;
    public static final int ERROR_NOT_ENOUGH_STOCK_FOR_ITEM = 207;
    public static final int ERROR_NO_PRODUCT_SPECIFIED = 208;
    public static final int ERROR_NO_PRODUCT_CATEGORY_SPECIFIED = 209;
    public static final int ERROR_NO_WAREHOUSE_SPECIFIED = 210;
    public static final int ERROR_NO_START_DATE_SPECIFIED = 211;
    public static final int ERROR_NO_END_DATE_SPECIFIED = 212;
    public static final int ERROR_NO_COMPANY_EMAIL_IS_SPECIFIED = 213;
    public static final int ERROR_NO_ITEM_IN_THE_CART = 214;
    public static final int ERROR_USER_IS_NOT_ENABLED = 215;
    //    public static final int ERROR_NO_TENANT = 25;
//    public static final int ERROR_CANT_FIND_SPECIFIED_OBJECT = 26;
   
}
